language: python
#cache: true

# We don't actually use the Travis Python but conda
matrix:
  include:
    #- os: linux
    #- python: 2.7
    #- env: PYTHON_VERSION=2.7
    - os: linux
      python: 3.6
      env: PYTHON_VERSION=3.6

#dist: precise
sudo: false
install:
  #- sudo apt-get update
  - env

  # pip-based installation.
  #- travis_wait pip install -q -r requirements.txt
  #- travis_wait pip install -q -r requirements-optional.txt

  # Install conda https://conda.io/docs/travis.html
  - source dev_scripts/conda_installer.sh
  #- source dev_scripts/conda_develop.sh
  #- conda uninstall -y pymatgen
  #- conda install --file binder/environment.yml
  - conda install -y -c anaconda setuptools
  - conda env update --file=binder/environment.yml

  #- conda install -y --file ./requirements.txt
  - conda install -y --file ./requirements-optional.txt

  #- if [[ "${PYTHON_VERSION}" == "2.7" ]]; then conda install mock; fi
  #- pip install nose nose-exclude

  # Install abinit from abinit conda channel.
  #- conda install -c gmatteo abinit=8.6.1
  #- abinit --version
  #- abinit --build

  # Use gmatteo's pymatgen fork
  #- git clone --depth=50 https://github.com/gmatteo/pymatgen.git && cd pymatgen && pip install -r requirements.txt && pip install -r requirements-optional.txt && python setup.py install && cd ../

  #- git clone --depth=50 https://github.com/gmatteo/pymatgen.git && cd pymatgen && python setup.py install && cd ../

  # Use pymatgen master
  #- git clone --depth=50 https://github.com/materialsproject/pymatgen.git && cd pymatgen && pip install -r requirements.txt && pip install -r requirements-optional.txt && python setup.py install && cd ../

  #- python setup.py install
  #- mkdir -p ${HOME}/.abinit/abipy 
  #- cp abipy/data/managers/travis_scheduler.yml ${HOME}/.abinit/abipy/scheduler.yml
  #- cp abipy/data/managers/travis_manager.yml ${HOME}/.abinit/abipy/manager.yml
  #- ./dev_scripts/pyclean.py .

before_script:
    # This to run tests requiring a graphical user e.g. mayavi
    # https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
    #- "export DISPLAY=:99.0"
    #- "sh -e /etc/init.d/xvfb start"
    #- sleep 3 # give xvfb some time to start
    # https://github.com/travis-ci/travis-ci/issues/6307
    #- if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then rvm get head; fi 

# command to run tests
script: ./dev_scripts/runtests.sh

branches:
  only:
    - master

after_success:
  - if [[ "${PYTHON_VERSION}" == "3.6" && "${TRAVIS_OS_NAME}" == "linux" ]]; then coveralls; fi

notifications:
  email:
    recipients:
      - gmatteo@gmail.com
    on_success: change
    on_failure: always
