name: abitutorials linting

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Lint with pycodestyle
      run: |
        pip install pycodestyle
        pycodestyle abitutorials
      #- name: Lint with mypy
      #  run: |
      #    pip install mypy
      #    mypy abitutorials
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 --count --show-source --statistics abitutorials
        # exit-zero treats all errors as warnings.
        #flake8 --count --exit-zero --max-complexity=20 --statistics abitutorials
        #- name: Lint with pylint
        #  run: |
        #    pip install pylint
        #    # stop the build if there are Python syntax errors or undefined names
        #    pylint --exit-zero abitutorials
